import React, { ReactNode } from "react";
import { Inter, JetBrains_Mono } from "next/font/google";
import "../../../app/globals.css";

// Fuente principal (Sans)
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const jetMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center">
      {children}
    </div>
  );
}


