FROM node:20 AS builder
WORKDIR /app
COPY package.json package-lock.json* ./

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY_V2
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_GOOGLE_CLIENT_SECRET
ARG NEXT_PUBLIC_GITHUB_CLIENT_ID
ARG NEXT_PUBLIC_DISCORD_CLIENT_ID
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

ENV NEXT_PUBLIC_API_URL=https://api.servineo.app
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=6LeUQhwsAAAAAB5UUMKX4gSp2O-LwVXbNLSmHasG
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY_V2=6LfVGxwsAAAAAEdjd6-qCKc9LhcIZRoWBCwlRU4J
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=830637764593-g8v6upkgq190ivcshbur0na84glb74m0.apps.googleusercontent.com
ENV NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=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
ENV NEXT_PUBLIC_GITHUB_CLIENT_ID=Ov23liHYTN9wLl434iRv
ENV NEXT_PUBLIC_DISCORD_CLIENT_ID=1437114348513398816
ENV NEXT_PUBLIC_BASE_URL=https://servineo.app
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51SHGq0Fp8K0s2pYx4l5z1fkIcXSouAknc9gUV6PpYKR8TjexmaC3OiJR9jNIa09e280Pa6jGVRA6ZNY7kSCCGcLt002CEmfDnU

RUN npm install --frozen-lockfile || npm install
COPY . .
RUN npm run build


FROM node:20 AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_PUBLIC_API_URL=https://api.servineo.app
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=6LeUQhwsAAAAAB5UUMKX4gSp2O-LwVXbNLSmHasG
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY_V2=6LfVGxwsAAAAAEdjd6-qCKc9LhcIZRoWBCwlRU4J
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=830637764593-g8v6upkgq190ivcshbur0na84glb74m0.apps.googleusercontent.com
ENV NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=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
ENV NEXT_PUBLIC_GITHUB_CLIENT_ID=Ov23liHYTN9wLl434iRv
ENV NEXT_PUBLIC_DISCORD_CLIENT_ID=1437114348513398816
ENV NEXT_PUBLIC_BASE_URL=https://servineo.app
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51SHGq0Fp8K0s2pYx4l5z1fkIcXSouAknc9gUV6PpYKR8TjexmaC3OiJR9jNIa09e280Pa6jGVRA6ZNY7kSCCGcLt002CEmfDnU

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000
CMD ["npm", "start"]
