  Qabranch[m
  dev[m
  ft/sp3[m
  int-dev[m
  int2.1[m
  prueba-int-whit-home[m
  pruebaQA[m
  stable-integration[m
  stable-version-2[m
  v[m
* [32mv2[m
  [31mremotes/Erick-SOS/HEAD[m -> Erick-SOS/dev
  [31mremotes/Erick-SOS/alt[m
  [31mremotes/Erick-SOS/dev[m
  [31mremotes/Erick-SOS/extra[m
  [31mremotes/Erick-SOS/ft/fix[m
  [31mremotes/Erick-SOS/ft/graphics[m
  [31mremotes/Erick-SOS/ft/profile[m
  [31mremotes/Erick-SOS/ft/sp3[m
  [31mremotes/Erick-SOS/integration-with-ByteBandidos[m
  [31mremotes/Erick-SOS/stable[m
  [31mremotes/Erick-SOS/v2[m
  [31mremotes/origin/HEAD[m -> origin/dev
  [31mremotes/origin/Int-log[m
  [31mremotes/origin/bugFix/component-login[m
  [31mremotes/origin/dev[m
  [31mremotes/origin/feature/FixerForm-compoment[m
  [31mremotes/origin/feature/become-fixer[m
  [31mremotes/origin/feature/bugfix-cards[m
  [31mremotes/origin/feature/bugfix-map[m
  [31mremotes/origin/feature/bugfix-myoffers[m
  [31mremotes/origin/feature/bugfix-step-component[m
  [31mremotes/origin/feature/component-profile-fixer[m
  [31mremotes/origin/feature/dasboardFixer[m
  [31mremotes/origin/feature/fixer-schemas[m
  [31mremotes/origin/feature/integration-temp[m
  [31mremotes/origin/feature/integrations-components[m
  [31mremotes/origin/feature/lis-offer-jobs[m
  [31mremotes/origin/feature/map-component[m
  [31mremotes/origin/feature/step-fixer[m
  [31mremotes/origin/feature/tabs-component[m
  [31mremotes/origin/int-v1[m
  [31mremotes/origin/integration-with-ByteBandidos[m
  [31mremotes/origin/integration-with-filters-v2[m
  [31mremotes/origin/integration-with-filters-v3[m
  [31mremotes/origin/integration-with-home[m
  [31mremotes/origin/integration-with-login[m
  [31mremotes/origin/integration-with-lumon[m
  [31mremotes/origin/integrations-components-v2[m
  [31mremotes/origin/integrations-lorem[m
  [31mremotes/origin/prueba-int-whit-home[m
  [31mremotes/origin/pruebaQA[m
  [31mremotes/origin/stable-integration[m
  [31mremotes/origin/stable-version-2[m
  [31mremotes/origin/stable-version-2.1[m
  [31mremotes/origin/stable-version-2.2[m
  [31mremotes/origin/updatePruebaQa[m
