import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { roboto } from './fonts';
import 'leaflet/dist/leaflet.css';
import { Providers } from './providers';
import { AuthProvider } from './lib/hooks/usoAutentificacion';
import TopMenu from '@/Components/Navigation/TopMenu';
import FooterSection from '@/Components/Home/Footer-section';
import { TourLogic } from '@/Components/Tour/TourLogic';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.className} `}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}>
        <Providers>
          <AuthProvider>
            <TourLogic />
            <div className="">
              <TopMenu />
            </div>
            {children}
            <FooterSection />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
