import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import { roboto } from '../fonts';
import 'leaflet/dist/leaflet.css';
import { Providers } from '../providers';
import TopMenu from '@/Components/Navigation/TopMenu';
import { ReactNode } from 'react';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import { TranslationButton } from '@/Components/Shared/TranslationButton';
import BotonesFlotantes from '@/Components/ask_for_help/contenedor';
import FooterSection from '@/Components/Home/Footer-section';
import { TourLogic } from '@/Components/Tour/TourLogic';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const messagesMap = {
  en: () => import('../../../messages/en.json').then((mod) => mod.default),
  es: () => import('../../../messages/es.json').then((mod) => mod.default),
};

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'es' }];
}

export const metadata: Metadata = {
  title: 'Servineo',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  const validLocales = ['en', 'es'];
  if (!validLocales.includes(locale)) notFound();

  const loader = messagesMap[locale as keyof typeof messagesMap];
  if (!loader) notFound();

  const messages = await loader();

  return (
    <html lang={locale} className={`${roboto.className}`}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning={true}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>
            {/* ESTA LÍNEA ES LA QUE HACE QUE LA GUÍA FUNCIONE */}
            <TourLogic />
           
            <div className="text-black fixed bottom-7 right-7 z-[9999]">
              <TranslationButton />
            </div>
            <div className="">
              <BotonesFlotantes />
            </div>
            <div className="">
              <TopMenu />
            </div>
            {children}
            <FooterSection />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}