import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import { roboto } from '../fonts';
import 'leaflet/dist/leaflet.css';
import { ReduxProvider } from '../redux/ReduxProvider';
import TopMenu from '@/Components/Navigation/TopMenu';
import { ReactNode } from 'react';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import { TranslationButton } from '@/Components/Shared/TranslationButton';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const messagesMap = {
  en: () => import('../../../messages/en.json'),
  es: () => import('../../../messages/es.json'),
};

export const metadata: Metadata = {
  title: 'Servineo',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const loader = messagesMap[locale as keyof typeof messagesMap];
  if (!loader) notFound();
  const messages = (await loader()).default;
  return (
    <html lang={locale} className={`${roboto.className} `}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
        <ReduxProvider>
          <div className="">
            <TopMenu/>
          </div>
          {children}
          <TranslationButton/>
        </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
