import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import { roboto } from '../fonts';
import 'leaflet/dist/leaflet.css';
import { ReduxProvider } from '../redux/ReduxProvider';
import TopMenu from '@/Components/Navigation/TopMenu';
import { ReactNode } from 'react';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import { TranslationButton } from '@/Components/Shared/TranslationButton';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// Mapa de mensajes
const messagesMap = {
  en: () => import('../../../messages/en.json').then(mod => mod.default),
  es: () => import('../../../messages/es.json').then(mod => mod.default),
};

// Genera los locales estáticamente
export function generateStaticParams() {
  return [
    { locale: 'en' },
    { locale: 'es' }
  ];
}

export const metadata: Metadata = {
  title: 'Servineo',
  description: 'Generated by create next app',
};

// Tipos para los params
type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  // Validar el locale
  const validLocales = ['en', 'es'];
  if (!validLocales.includes(locale)) {
    notFound();
  }

  // Cargar mensajes de forma segura
  const loader = messagesMap[locale as keyof typeof messagesMap];
  if (!loader) {
    notFound();
  }

  const messages = await loader();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ReduxProvider>
            <div className="text-black fixed bottom-7 right-7 z-[9999]">
              <TranslationButton />
            </div>
            <div className="">
              <TopMenu />
            </div>
            {children}
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}